#!/bin/bash
export FOX_BUILD_DEVICE="lancelot"
export OF_MAINTAINER="frieren"
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export OF_USE_NEW_MAGISKBOOT=1
export OF_DEFAULT_KEYMASTER_VERSION=4.0
export OF_INCLUDE_FBE_METADATA_DECRYPT=1
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export FOX_BUILD_TYPE="Unofficial"
export OF_SCREEN_H=2340
export OF_STATUS_H=80
export OF_FORCE_USE_RECOVERY_FSTAB=0
