#!/bin/bash
export FOX_BUILD_DEVICE="lancelot"
export OF_MAINTAINER="frieren"
export FOX_BUILD_TYPE="Unofficial"
export OF_DEFAULT_KEYMASTER_VERSION=4.0
export OF_INCLUDE_FBE_METADATA_DECRYPT=1
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export OF_SCREEN_H=2340
export OF_STATUS_H=80
export OF_NO_ADDITIONAL_MIUI_PROPS_CHECK=1
export TARGET_DEVICE_ALT="shiva"
export FOX_TARGET_DEVICES="lancelot,shiva"
export OF_SKIP_FBE_DECRYPTION=1

